### PR TITLE
Fix current hadolint and container-scan CI problems

### LINKED ISSUE #34: Schedule periodic tests
As suggested in https://github.com/orise-robotics/ros_ws/pull/33#issuecomment-776644325. The intention is to capture errors as they occur. This update can also include updating the badges in the README file

### PR DESCRIPTION
**Pull request by mateus-amarante**
### Description
- Fix hadolint problem by ignoring version-pinning checks. I prefer to put effort into adapting to the latest versions of the dependencies and only pin versions when necessary and by demand
- Fix vulnerability problems by ~~upgrading all packages~~ installing security updates with `unattended-upgrades`. One downside of this step is that it takes a bit longer to build the image, ~~especially considering it also update ROS packages from the `ros-$distro-base` base image~~. However, it seems to solve most of the problems
- ~~Try to set ignore-unfixed flag used in container-scan check through [trivy](https://github.com/aquasecurity/trivy)~~ (the result was the same, so I'll keep without it)
- Setup periodic tests to avoid more surprises in the future

### Related Issues:
- closes #34

### CODE REVIEW

**Comment by mateus-amarante** [comment]
@ivan1993br @caioaamaral friendly ping (this is impacting other 2 PRs)

**Review by ivan1993br — APPROVED** [review]
Nice!

**Review by ivan1993br — APPROVED** [review]
Nice!

**Review by caioaamaral — APPROVED** [review]
Nice addition!

**Pull request merged**
