### PR TITLE
Reference vscode_ros2_ws repo in README

### LINKED ISSUE #2: Create a common vscode workspace settings
I suggest creating a checklist of configurations we want to have in our workspace:
- Default extensions
- Linters & formatters:
  - c++
  - python
  - xml
  - cmake
  - yaml
...

### PR DESCRIPTION
**Pull request by mateus-amarante**
Close https://github.com/orise-robotics/ros_ws/issues/2

Depends on #35

### CODE REVIEW

**Review by ivan1993br — COMMENTED** [review]
Nice! Ow, what happened to the tests?

**Comment by mateus-amarante** [comment]
> Nice! Ow, what happened to the tests?

Container vulnerabilities and updates of the linter. I'll fix them in another PR. I also suggest scheduling periodic tests so we can capture these types of problems when they occur.

**Comment by ivan1993br** [comment]
>  I also suggest scheduling periodic tests so we can capture these types of problems when they occur.

Agreed

>Container vulnerabilities and updates of the linter.

This vulnerabilities were not here before, so there was an update there also

> I'll fix them in another PR.

Ok, I just think that we should not merge another PR (besides this one, and the other - as they were open before knowing the problemm and are simple PRs) before doing this fix, or the tests will always fail and we will not know what caused the problem

**Review by ivan1993br — APPROVED** [review]

**Comment by mateus-amarante** [comment]
> Ok, I just think that we should not merge another PR (besides this one, and the other - as they were open before knowing the problemm and are simple PRs) before doing this fix, or the tests will always fail and we will not know what caused the problem

I agree, my plan is to merge this other PR first

**Pull request merged**
